export const SPEC_KEY_MAP = {
  Brand: "brand",
  LaunchYear: "launchedYear",
  Display: "display",
  Weight: "mobileWeight",
  RefreshRate: "refreshRate",
  Processor: "processor",
  RAM: "ram",
  Storage: "storage",
  FrontCamera: "frontCamera",
  BackCamera: "backCamera",
  Camera: "camera",
  Battery: "battery",
  Charging: "charging",
  OS: "os",
  Price: "price",
  Availability: "available",
};

export const SPEC_ORDER = [
  "Brand",
  "LaunchYear",
  "Display",
  "Weight",
  "RefreshRate",
  "Processor",
  "RAM",
  "Storage",
  "FrontCamera",
  "BackCamera",
  "Camera",
  "Battery",
  "Charging",
  "OS",
  "Price",
  "Availability"
];
