create table if not exists public.devices (
  id text primary key,
  brand text not null,
  model text not null,
  category text,
  price numeric,
  payload jsonb not null
);

create index if not exists idx_devices_brand on public.devices (brand);
create index if not exists idx_devices_category on public.devices (category);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_users_email on public.users (email);
